# Generated by Django 4.1 on 2022-09-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_importancia_deleted_alter_tarea_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaetiqueta',
            name='etiqueta',
            field=models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, related_name='etiquetaTarea', to='gestion.etiqueta'),
        ),
        migrations.AlterField(
            model_name='tareaetiqueta',
            name='tarea',
            field=models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='tareaEtiqueta', to='gestion.tarea'),
        ),
    ]
